### PR TITLE
You have GOTTA merge this! 😄 

### PR DESCRIPTION
**Pull request by cyber-ocelot**
I saved my notebook so that the output is shown, it is AMAZING!!!!!!! :octocat: 🥳

### CODE REVIEW

**Comment by tproffen** [comment]
Done as requested :)

**Comment by cyber-ocelot** [comment]
yay!! 🥳

**Comment by cyber-ocelot** [comment]
but it seems the pics are to big to be seen, so I'm going to change their size

**Comment by cyber-ocelot** [comment]
nevermind, solved it a different way

**Pull request merged**
